export const ACTIONS = {
    SET_TOKEN: 'SET_TOKEN',
    SET_PROFILE: 'SET_PROFILE',
    SET_SELECTED_MOVIE: 'SET_SELECTED_MOVIE',
    SET_ADD_TO_LIST_MODAL_VISIBLITY: 'SET_ADD_TO_LIST_MODAL_VISIBLITY',
    SET_NEW_LIST_MODAL_VISIBLITY: 'SET_NEW_LIST_MODAL_VISIBLITY',
};
